### ISSUE TITLE
Использовать сайдбар по назначению - для навигации

### ISSUE THREAD

**Issue by MihaxXx** [TonySatrem/CC_Games#10]
Справку о вашем сайте следует вынести на отдельную страницу, которая будет вызываться по кнопке "i" где-то, а в сайдбаре стоит сделать навигацию по играм, т.е. быстрое пролистывание до нужного пункта, раз уж они на одной странице

**Comment by Volkir94** [comment]
https://github.com/TonySatrem/CC_Games/pull/13
