### ISSUE TITLE
Заголовок меню дёргается при наведении на пункты меню

### ISSUE THREAD

**Issue by MihaxXx** [TonySatrem/CC_Games#9]
При наведении на пункты меню, шрифт выбранного пункта увеличивается. В целом, наверное, ок, что другие пункты чуть сдвигаются, но заголовок точно не должен никуда уезжать. Вероятно, нужно задать фиксированную высоту контейнеру списка пунктов меню по его максимальному размеру

**Comment by Volkir94** [comment]
https://github.com/TonySatrem/CC_Games/pull/13
